name: ETL Pipline

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
          

jobs:
    etl_pipline:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Setting up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Libraries Installations
          run: pip install pandas requests datetime

        - name: Run the scripts
          run: python apps.py

        - name: Publish files to github repo
          uses: mikeal/publish-to-github-actions@master
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            BRANCH_NAME: 'Master'



